CREATE SCHEMA `pizzaria` DEFAULT CHARACTER SET utf8;

CREATE TABLE IF NOT EXISTS `PIZZARIA`.`STATUS` (
  `STATUS` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador Status do Registro (FK) Tabela Status',
  `NM_STATUS` VARCHAR(45) NOT NULL COMMENT 'Nome status',
  `DSC_STATUS` VARCHAR(255) NULL COMMENT 'Descricao status do registro',
  `DT_CRI` DATETIME NOT NULL COMMENT 'Data Criação do registro na base',
  `DT_ULT_ALT` DATETIME NOT NULL COMMENT 'Data da Ultima Alteracao do registro',
  PRIMARY KEY (`STATUS`)
);

INSERT INTO `pizzaria`.`STATUS` (`NM_STATUS`, `DSC_STATUS`, `DT_CRI`, `DT_ULT_ALT`) VALUES ('ATIVO', 'Registro ativo valido na base', '2020-04-25 04:30:00', '2020-04-25 04:30:00');


CREATE TABLE IF NOT EXISTS `PIZZARIA`.`BEBIDAS` (
  `BEBIDA` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador bebida',
  `NM_BEBIDA` VARCHAR(45) NOT NULL COMMENT 'Nome da bebida',
  `VL_BEBIDA` DECIMAL(6,2) NOT NULL COMMENT 'Valor da bebida',
  `DSC_BEBIDA` VARCHAR(255) NULL COMMENT 'Descricao da bebida',
  `STATUS` INT NOT NULL COMMENT 'Identificador Status do Registro (FK) Tabela Status',
  `DT_CRI` DATETIME NOT NULL COMMENT 'Data Criação do registro na base',
  `DT_ULT_ALT` DATETIME NOT NULL COMMENT 'Data da Ultima Alteracao do registro',
  PRIMARY KEY (`BEBIDA`),
  INDEX `FKBEBIDASTATUS_idx` (`STATUS` ASC),
  CONSTRAINT `FKBEBIDASTATUS`
    FOREIGN KEY (`STATUS`)
    REFERENCES `PIZZARIA`.`STATUS` (`STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `PIZZARIA`.`CLIENTE` (
  `CLIENTE` INT NOT NULL AUTO_INCREMENT COMMENT 'identificador cliente',
  `NM_CLIENTE` VARCHAR(45) NOT NULL COMMENT 'Nome do Cliente',
  `ENDERECO` VARCHAR(255) NOT NULL COMMENT 'Endereco de entrega do cliente',
  `TELEFONE` VARCHAR(15) NOT NULL COMMENT 'Telefone de contato do cliente',
  `STATUS` INT NOT NULL COMMENT 'Identificador Status do Registro (FK) Tabela Status\n',
  `DT_CRI` DATETIME NOT NULL COMMENT 'Data Criação do registro na base',
  `DT_ULT_ALT` DATETIME NOT NULL COMMENT 'Data da Ultima Alteracao do registro',
  PRIMARY KEY (`CLIENTE`),
  INDEX `FKCLIENTESTATUS_idx` (`STATUS` ASC),
  CONSTRAINT `FKCLIENTESTATUS`
    FOREIGN KEY (`STATUS`)
    REFERENCES `PIZZARIA`.`STATUS` (`STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);


CREATE TABLE IF NOT EXISTS `PIZZARIA`.`SABORES` (
  `SABOR` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador Sabor',
  `NM_SABOR` VARCHAR(45) NOT NULL COMMENT 'Nome do sabor',
  `VL_SABOR` DECIMAL(6,2) NOT NULL COMMENT 'Valor do sabor',
  `DSC_SABOR` VARCHAR(255) NULL COMMENT 'Descricao do Sabor em questão do registro',
  `STATUS` INT NOT NULL COMMENT 'Identificador Status do Registro (FK) Tabela Status',
  `DT_CRI` DATETIME NOT NULL COMMENT 'Data Criação do registro na base',
  `DT_ULT_ALT` DATETIME NOT NULL COMMENT 'Data da Ultima Alteracao do registro',
  PRIMARY KEY (`SABOR`),
  UNIQUE INDEX `NM_SABOR_UNIQUE` (`NM_SABOR` ASC),
  INDEX `FKSABORSTATUS_idx` (`STATUS` ASC),
  CONSTRAINT `FKSABORSTATUS`
    FOREIGN KEY (`STATUS`)
    REFERENCES `PIZZARIA`.`STATUS` (`STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `PIZZARIA`.`OUTROS` (
  `OUTRO` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador outro item',
  `NM_OUTRO` VARCHAR(45) NOT NULL COMMENT 'Nome do item',
  `VL_OUTRO` DECIMAL(6,2) NOT NULL COMMENT 'Valor do item',
  `DSC_OUTRO` VARCHAR(255) NULL COMMENT 'Descricao do item em questao do registro',
  `STATUS` INT NOT NULL COMMENT 'Identificador Status do Registro (FK) Tabela Status',
  `DT_CRI` DATETIME NOT NULL COMMENT 'Data criacao do registro na base',
  `DT_ULT_ALT` DATETIME NOT  NULL COMMENT 'Data da ultima alteracao do registro',
  PRIMARY KEY (`OUTRO`),
  UNIQUE INDEX `NM_OUTRO_UNIQUE` (`NM_OUTRO` ASC),
  INDEX `FKOUTROSTATUS_idx` (`STATUS` ASC),
  CONSTRAINT `FKOUTROSTATUS`
    FOREIGN KEY (`STATUS`)
    REFERENCES `PIZZARIA`.`STATUS` (`STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS `PIZZARIA`.`PEDIDO` (
  `PEDIDO` INT NOT NULL AUTO_INCREMENT COMMENT 'Identificador pedido',
  `VL_PEDIDO` DECIMAL(6,2) NOT NULL COMMENT 'Valor do pedido',
  `NM_CLIENTE` VARCHAR(45) NOT NULL COMMENT 'Nome do Cliente',
  `ENDERECO` VARCHAR(255) NOT NULL COMMENT 'Endereco de entrega do cliente',
  `SABOR` INT NOT NULL COMMENT 'Identificador sabor',
  `BEBIDA` INT NOT NULL COMMENT 'Identificador Bebida',
  `OUTRO` INT NOT NULL COMMENT 'Identificador Outro',
  `OBSERVACAO` VARCHAR(255) NULL COMMENT 'Observacoes dentre o pedido em questao, ex: Pizzas sem cebolas, Casa do fundo etc...',
  `STATUS` INT NOT NULL COMMENT 'Identificador Status do Registro (FK) Tabela Status',
  `DT_CRI` DATETIME NOT NULL COMMENT 'Data Criação do registro na base',
  `DT_ULT_ALT` DATETIME NOT NULL COMMENT 'Data da Ultima Alteracao do registro',
  PRIMARY KEY (`PEDIDO`),
  INDEX `FKPEDIDOSABOR_idx` (`SABOR` ASC),
  INDEX `FKPEDIDOSTATUS_idx` (`STATUS` ASC),
  INDEX `FKPEDIDOBEBIDA_idx` (`BEBIDA` ASC),
  INDEX `FKPEDIDOOUTRO_idx` (`OUTRO` ASC),
  CONSTRAINT `FKPEDIDOSABOR`
    FOREIGN KEY (`SABOR`)
    REFERENCES `PIZZARIA`.`SABORES` (`SABOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPEDIDOOUTRO`
    FOREIGN KEY (`OUTRO`)
    REFERENCES `PIZZARIA`.`OUTROS` (`OUTRO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPEDIDOSTATUS`
    FOREIGN KEY (`STATUS`)
    REFERENCES `PIZZARIA`.`STATUS` (`STATUS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FKPEDIDOBEBIDA`
    FOREIGN KEY (`BEBIDA`)
    REFERENCES `PIZZARIA`.`BEBIDAS` (`BEBIDA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
);

INSERT INTO `pizzaria`.`sabores` (`NM_SABOR`, `VL_SABOR`, `DSC_SABOR`, `STATUS`, `DT_CRI`, `DT_ULT_ALT`) VALUES ('Nenhum', '00.00', 'Nenhum', 1, '2020-04-25 04:30:00', '2020-04-25 04:30:00');
INSERT INTO `pizzaria`.`bebidas` (`NM_BEBIDA`, `VL_BEBIDA`, `DSC_BEBIDA`, `STATUS`, `DT_CRI`, `DT_ULT_ALT`) VALUES ('Nenhum', '00.00', 'Nenhum', 1, '2020-04-25 04:30:00', '2020-04-25 04:30:00');
INSERT INTO `pizzaria`.`outros` (`NM_OUTRO`, `VL_OUTRO`, `DSC_OUTRO`, `STATUS`, `DT_CRI`, `DT_ULT_ALT`) VALUES ('Nenhum', '00.00', 'Nenhum', 1, '2020-04-25 04:30:00', '2020-04-25 04:30:00');